### ISSUE TITLE
Блоки: Опечатка в классе, логика вывода классов типа блока, лишние пробелы в заголовке

### ISSUE THREAD

**Issue by philimonovvadim** [Niklan/Glisseo#10]
Я создал тип блока, который имеет машинное имя:
`block_with_image`
Потом разместил на страницу блок этого типа блока. Сам блок имеет машинное имя:
`test_block_with_picture`

Разметка получилось следующей:
```html
<div class="block-test-block-with-picture">
  <div class="block-test-block-with-picture__title">
      Test block with picture
  </div>
  <div class="block-content-block_with_image-full block-test-block-with-picture__content">
    <div class="block-content-block-with-image-full__body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>   
    </div>
    <div class="block-content-block-with-image-full__field-image">
      <img src="/path-to-image/image.jpg" width="480" height="320" alt="" typeof="foaf:Image">
      </div>
  </div>
</div>
```
### 1
Смотрим на класс:
`block-content-block_with_image-full`
У него нижнее подчеркивание не заменяется на тире.
А у элемента body уже все в порядке:
`block-content-block-with-image-full__body`

### 2
Почему классы блока применяются только на самый родитель и content, а класс типа блока для content и ниже?
Предлагаю сделать разметку следующей:
```html
<div class="block-test-block-with-picture block-content-block-with-image-full">
  <div class="block-test-block-with-picture__title block-content-block-with-image-full__title">
      Test block with picture
  </div>
  <div class="block-test-block-with-picture__content block-content-block-with-image-full__content">
    <div class="block-test-block-with-picture__body block-content-block-with-image-full__body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>   
    </div>
    <div class="block-test-block-with-picture__field-image block-content-block-with-image-full__field-image">
      <img src="/path-to-image/image.jpg" width="480" height="320" alt="" typeof="foaf:Image">
      </div>
  </div>
</div>
```

### 3
У заголовка много лишних пробелов. Нужно сделать что-то типа?
`{{- label -}}`
![image](https://user-images.githubusercontent.com/28534205/54880550-9f671e00-4e56-11e9-8f91-cdd4320dabdb.png)

**Comment by Niklan** [comment]
1. Странно, по исходнику не вижу проблемы, надо будет потестить.

В [блоке](https://github.com/Niklan/Glisseo/blob/8.x-1.x/templates/content/block/block.html.twig) мы задаем bem_block.

```twig
{% set bem_block = bem_block ?: 'block-' ~ block_id|split('__', 2)|first|clean_class %}
```

В конце он проходит через фильтр `clean_class`, который и заменяет нижние подчеркивания на тире.

А затем он используется для формирования всех классов, включая тот, где проблема:

```twig
<div{{ content_attributes.addClass(bem_block ~ '__content') }}>
```

В общем, надо поковырять будет.

Что это за тип блока, мне надо понять чтобы проверять.

2. Потому что блок, и содержимое блока - это две разные сущности. И внутри сущности блока-содержимого, уже ничего не известно о блоке-конфигурации, поэтому классы унаследовать без костылей нереально. Это две разных сущности, не вижу сейчас никакой возможности это реализовать. 

3. Проверю.

Если есть фикс по первом и третьему вопросу, можно слать пул реквестом, проверю. По второму, на данный момент я могу его пометить лишь как "works as designed", так как это особенность работы блоков в ядре друпала, и тема тут бессильна.
