### ISSUE TITLE
 Unknown "dd" function

### ISSUE THREAD

**Issue by KitsuneSolar** [Niklan/Glisseo#3]
![screenshot_2018-08-08 details dev drupal](https://user-images.githubusercontent.com/12877339/43808284-05445ca2-9ab5-11e8-8952-e4b6ad1001e2.png)

**Comment by kovtunos** [comment]
Install Twig_tweak module. It's from there.

**Comment by Niklan** [comment]
Thank you, fixed in current dev, will be released with alpha9.
