### ISSUE TITLE
Label for title of menu block.

### ISSUE THREAD

**Issue by lukasvs** [Niklan/Glisseo#7]
https://github.com/Niklan/Glisseo/blob/8b14065a23a36cdaa9f28621c9b3440725d01f3f/templates/content/block/block--system-menu-block.html.twig#L24

This may be skipped: 
{% if label %}
{% endif %}

**Comment by Niklan** [comment]
Also wrap

```twig
{% if configuration.label %}
  {% do attributes.setAttribute('aria-labelledby', heading_id) %}
{% endif %}
```
