### ISSUE TITLE
view_mode is empty

### ISSUE THREAD

**Issue by lukasvs** [Niklan/Glisseo#9]
https://github.com/Niklan/Glisseo/blob/2f4482542fbcba018a4c360219518ad3e866a36d/templates/content/user/user.html.twig#L1

I get the empty value for view_mode of user.
I think there is not enough preprocessor for user.

**Comment by Niklan** [comment]
Fixed, thank you.

**Comment by Niklan** [comment]
Reopen since there can be a bug.

Need to test render user template with different view modes. View possible not stored in `$variables['view_mode']` instead it stored in `$variables['element']`.

**Comment by Niklan** [comment]
The core doesn't add variable `view_mode` for the user, so we do that in the base theme.
